---
title: "aDNA Electronic Lab Notebook"
author: "Ethan Thibault"
date: "11/14/2018"
output:
  html_document:
    df_print: paged
---

# Description of notebook

This document will be used as the notebook for the NSF Spruce aDNA project. We need to use an online notebook because the aDNA room is susceptible to contamination and we cannot be moving a physical notebook back and forth from the regular lab to the aDNA lab.

# Table of Contents:

* [Page 1: February 28, 2019](#id-section1). Bring in supplies
* [Page 2: March 5, 2019](#id-section2). Make Extraction Solutions
* [Page 3: March 6, 2019](#id-section3). Make Extraction Solutions
* [Page 4: March 8, 2019](#id-section4). First Extraction!
* [Page 5: March 22, 2019](#id-section5). Singleplex Prep
* [Page 6: March 29, 2019](#id-section6). Tray 1 Singleplex Loci 06/07 Prep
* [Page 7: April 15, 2019](#id-section7). Tray 1 Singleplex Loci 01/02 Prep
* [Page 8: April 23, 2019](#id-section8). Tray 1 Singleplex Loci 17/18 Prep
* [Page 9: April 24, 2019](#id-section9). Tray 1 Singleplex Loci 05/04 Prep
* [Page 10: April 26, 2019](#id-section10). Tray 1 Singleplex Loci 15/16 Prep
* [Page 11: May 1, 2019](#id-section11). Tray 2 aDNA Extraction and Multiplex
* [Page 12: May 8, 2019](#id-section12). Singplex Prep for Tray 2

------

<div id='id-section1'/>

### Page 1: February 28, 2019, Bring in supplies

I brought in the new tips today that fit the 10ul multichannel pipette. I also brought in the trash can, weigh boats, syringes, and filters. I am cycling the syringes, filters, and weigh boats through the UV cycle in the hood. I am taking out an Endura plate to see if the robot will be able to recognize it. I will not be able to take out the full skirt plates we recieved the pollen in. This could potentially be an issue because I am not sure that the full skirt will allow for the wells to actually sit in the heqat block of the thermal cycler... So it turns out I cannot even close the thermal cycler with the full skirted plat in there... this is going to be an issue that I need to talk to Steve about. It is too late to ask the collaboraters sorting the pollen to put them into different plates... Good news is that it looks like pipetting 2ul from one ml from the trough using the multichannel will work just fine. It also appears that I cannot log into my gmail on this computer because it doesn't recognize the device and wants to text me a code, but I can't have my phone in here. This computer also appears to not have speakers built in so I cannot listen to music unless I get some speakers for this room.

------

<div id='id-section2'/>

### Page 2: March 5, 2019, Make Extraction Solutions

I just bought two new bottles of bleach (one for the main lab and one for the aDNA lab), two 1 liter bottles that I filled with ddH2O from the TA prep room on the first floor of Jeffords. One will become the transfer vessel and the other stay in the aDNA room. I also got funnels for transfering the ddH2O and got the scoopulas and trashbags from amazon. I am going to go into the aDNA room, make new 10% bleach, bleach and UV things I am bringing into the lab, make solutions, check that the semi skirted endura plates fit in the thermal cycler (try closing it). I will then come out and bleach the heat block (which we will use for the DNA extraction step instead of the thermal cycler and transfer the volume once the multiplex mix has been added to the semi skirted plates. Below are the instructions for making the solutions I need. Leave with pH tape so that I can make the 1M Tris-HCl in the main lab.

10% SDS

1.5g SDS + enough ddH2O to bring up to 15ml on the conical tube.

0.25M EDTA

4.383g EDTA + enough water to dissolve EDTA. Check ph is 8.

UV irradiate all of those solutions under the hood

*In aDNA room*

I have made new 10% bleach and am UVing the water scoopula and funnel. Also, the semi skirted plate does fit in the thermal cycler thank goodness. I made the SDS but I am having trouble with the EDTA and I think I need to add NaOH and I also think I may have gotten the calculation wrong so I need to do some figuring back at my office.

------

<div id='id-section3'/>

### Page 3: March 6, 2019, Make Extraction Solutions

Anoob grabbed the Tris from the main lab and so the first thing I am going to do is grab the bleach squirt bottle from the aDNA lab to wipe down the outside of that container.

In the aDNA lab I will check that the full skirted plates fit in the heat block then hook up the heat block in the hood and UV it.

I will measure out Tris into a 15ml conical tube and EDTA into a 15ml conical tube

Tris --> 1.8171g 

EDTA --> 1.0959g

Bring those volumes up to around 10ml. Take a few kim wipes to rest the tubes on in the main lab and bring some pH paper as well.

Bleach workspace in main lab to add HCl to Tris and NaOH to EDTA to pH Tris HCl to 7.8 and EDTA to pH 8. Wipe down the outsides with bleach, and zap with UV in biosafety cabinet. Bring these to my office until tomorrow.

*In aDNA lab*

The fully skirted plate does fit in the heat block.

------

<div id='id-section4'/>

### Page 4: March 8, 2019, First Extraction!

Below is the protocol for the day:

* Get 10% bleach from aDNA room  
* Bleach outside of solutions and outside of primer tubes  
* Here are the primer dilutions:  
* 01 --> 311ul  
* 02 --> 311ul  
* 04 --> 300ul  
* 05 --> 273ul  
* 06 --> 356ul  
* 07 --> 275ul  
* 13 --> 338ul  
* 14 --> 291ul  
* 15 --> 337ul  
* 16 --> 307ul  
* 17 --> 325ul  
* 18 --> 276ul  

* Bring things to aDNA room  
* Pour ddH2O into heat block and set to 56C  
* UV solutions, tips, pipettes and troughs (and multiple tubes of nfH20)   
* Bring solutions up to volume (15ml)  
* Dilute primers  
* Add 10ul of each primer stock to a tube with 380ul nfH2O for master primer mix  
* In separate 1.5ml tubes put 1200ul nfH2O, 500ul 0.25M EDTA, 500ul 1M Tris-HCl, 500ul 10% SDS  
* Place these and syringe and filter under UV  
* In new 1.5ml tube add: 1ul 10% SDS, 10ul 1M Tris-HCl, 40ul 0.25M EDTA, 5ul 20mg/ml Prot K, 944ul nfH2O  
* Attach syringe to filter with plunger removed, add 1000ul of the above solution to the syringe and depress plunger to push solution into new 1.5ml tube  
* Transfer solution to trough and bring out the first plate on the cold block  
* Use multichannel to add 2ul to each well  
* Gently tap down all the liquid and add foil seal  
* Place on heat block for 60 mins  
* Make multiplex MM (20ul reaction volumes)  
* Mix following solutions in trough: 576ul nfH20, 1152ul Multiplex MM, 230.4ul Primer MM  
* Remove plate, dry off with kimwipe, and wipe down outside with bleach  
* Remove foil and trasfer by 8.5ul, 17ul of Multiplex PCR mix to each well, gently tap down  
* Transfer all to semiskirted plate, gently tap down  
* Cover with foil and bring to Phil's Lab to put on thermal cycler

------

<div id='id-section5'/>

### Page 5: March 22, 2019, Singleplex Prep

We are going to move forward with the first singleplex now that the robot is working. Below is the protocol I will follow.

* Bring gloves to aDNA room  
* Make a mix with 485.76ul H2O, 47.52ul 10uM Primer 13, 47.52 10uM Primer 14  
* Label one EnduraPlate with PCR MM and the other with Tray one 13/14 Singleplex  
* Cover Both plates and grab two extra seals  
* Bring an extra 1.5mL tube  
* MOVE TO MAIN LAB  
* Situate plates in robot and take out multiplex to thaw  
* Turn on the Thermal Cycler and start high program to bring to temperature  
* Add 792ul of Taq 2X Master Mix to primers and water  
* Dispense 171.6ul to each well of the first column of the PCR MM plate  
* Run program on the robot
* Seal plates and put in thermal cycler

------

<div id='id-section6'/>

### Page 6: March 29, 2019, Tray 1 Singleplex Loci 06/07 Prep

This protocol will start in the aDNA lab. Last night I UVed all of the things I will need for this experiment. The physical lab notebook has the actual calculations to get the numbers I will list below.

In aDNA lab make a mix in a 1.5ml tube of:

* 495.88ul H2O  
* 48.51ul Fw Primer 06 (10uM)  
* 48.51ul Rv Primer 07 (10uM)  

Label the Enduraplate as "Tray 1 06/07 Singleplex" with the date and my initials and seal the plate.

Bring two extra seals to the main lab.

MOVE TO THE MAIN LAB

Situate plates in the robot.

Turn on the thermal cycler and start the program.

Take out Multiplex plate to thaw.

Add 808.5ul of MyTaq 2X MM to 1.5ml tube.

Dispense 175.175ul of PCR MM into the second column of the wells on the PCR MM plate.

Run the program, seal the plates and place on the thermal cycler.

------

<div id='id-section7'/>

### Page 7: April 15, 2019, Tray 1 Singleplex Loci 01/02 Prep

This protocol will start in the aDNA lab. Friday I UVed all of the things I will need for this experiment.

In aDNA lab mix in a 1.5ml tube:

* 495.88ul H2O  
* 48.51ul Fw Primer 01 (10uM)  
* 48.51ul Rv Primer 02 (10uM)  

Label the Enduraplate as "Tray 1 01/02 Singleplex" with the date and my initials and seal the plate.

Bring two extra seals to the main lab.

MOVE TO THE MAIN LAB

Situate plates in the robot.

Turn on the thermal cycler and start the program.

Take out Multiplex plate to thaw.

Add 808.5ul of MyTaq 2X MM to 1.5ml tube.

Dispense 175.175ul of PCR MM into the second column of the wells on the PCR MM plate.

Run the program, seal the plates and place on the thermal cycler.

------

<div id='id-section8'/>

### Page 8: April 23, 2019, Tray 1 Singleplex Loci 17/18 Prep

Calculations can be found in the physical lab notebook.

In aDNA room mix in 1.5ml tube:

* 506ul Water  
* 49.5ul FW Primer 17 (10uM)  
* 49.5ul RV Primer 18 (10uM)

Label Enduraplate as "Tray 1 17/18 Singleplex" and seal

Bring 2 extra seals to the main lab

MOVE TO THE MAIN LAB

Situate plates in the robot

Turn on thermal cycler and start program

Take out multiplex plate to thaw

Add 825ul MyTaq 2X MM to the 1.5ml tube, votex, and spin down

Dispense 178.75ul PCR MM to the next column of free wells on the PCR MM plate (fix robot program accordingly)

Run program and seal plates

Place on thermal cycler and run program

------

<div id='id-section9'/>

### Page 9: April 24, 2019, Tray 1 Singleplex Loci 05/04 Prep

Calculations can be found in the physical lab notebook.

In aDNA room mix in 1.5ml tube:

* 516.12ul Water  
* 50.49ul FW Primer 05 (10uM)  
* 50.49ul RV Primer 04 (10uM)

Label Enduraplate as "Tray 1 05/04 Singleplex" and seal

Bring 2 extra seals to the main lab

MOVE TO THE MAIN LAB

Situate plates in the robot

Turn on thermal cycler and start program

Take out multiplex plate to thaw

Add 841.5ul MyTaq 2X MM to the 1.5ml tube, votex, and spin down

Dispense 182.325ul PCR MM to the next column of free wells on the PCR MM plate (fix robot program accordingly)

Run program and seal plates

Place on thermal cycler and run program

------

<div id='id-section10'/>

### Page 10: April 26, 2019, Tray 1 Singleplex Loci 15/16 Prep

Calculations can be found in the physical lab notebook.

In aDNA room mix in 1.5ml tube:

* 516.12ul Water  
* 50.49ul FW Primer 05 (10uM)  
* 50.49ul RV Primer 04 (10uM)

Label Enduraplate as "Tray 1 15/16 Singleplex" and seal

Bring 2 extra seals to the main lab

MOVE TO THE MAIN LAB

Situate plates in the robot

Turn on thermal cycler and start program

Take out multiplex plate to thaw

Add 841.5ul MyTaq 2X MM to the 1.5ml tube, votex, and spin down

Dispense 174ul PCR MM to the next column of free wells on the PCR MM plate (fix robot program accordingly)

Run program and seal plates

Place on thermal cycler and run program

------

<div id='id-section11'/>

### Page 11: May 1, 2019, Tray 1 aDNA Extraction and Multiplex

First thing when I get in the aDNA room is to check the thermal cycler program.

Put everything I will need/be using that arent primers or pollen, into the hood and zap with UV.

I have enough primer MM to use for this multiplex so I don't need to make more.

Put 500ul of each solution into new 1.5ml tubes:

* 0.25M EDTA  
* 1M Tris-HCl  
* 10% SDS  

Make many nfH2O aliquots.

Place the solutions and a syringe and filter into the hood and zap with UV.

In a new 1.5ml tube add:

* 1ul 10% SDS  
* 10ul 1M Tris-HCl  
* 40ul 0.25M EDTA  
* 5ul 20mg/ml Proteinase K  
* 944ul nfH2O  

Attach syringe to filter with plunger removed, add 1000ul of the above solution to the syringe, replace plunger and depress solution into a new 1.5ml tube.

Transfer solution to a trough.

Bring out tray and place on cold block.

Use multichannel to add 2ul to each well.

Tap down the liquid gently and add a foil seal.

Place in thermal cycler and run program:

* 56C for 60mins  
* 95C for 10mins  
* 4C hold  

In a new trough mix:

* 576ul nfH2O  
* 1152ul Multiplex MM  
* 230.4ul Primer MM

Remove plate from thermal cycler.

Transfer 7ul PCR Multiplex mix from trough to column on the plate and mix up and down.

Switch to 10/11ul and transfer that volumn to a new plate.

Do this for each column then transfer 10ul of PCR Multiplex mix from the trough to each well giving 96, 20ul reactions.

Gently tap plate down and add the foil seal.

Bring to Phil's lab and place on thermal cycler (35 cycles):

* 95C for 15mins  
* 94C for 30secs  
* 57C for 90secs  
* 72C for 90secs  
* 72C for 10mins  
* 4C hold  

------

<div id='id-section12'/>

### Page 12: May 8, 2019, Singleplex Prep for Tray 2

Caclulations can be found in the notebook, but what I need to do in the aDNA room is prep primer/water parts of the singleplex, put them into a plate that will be pulled from by the robot and bring the rest of the supplies I will need.

Before doing anything I need to UV 14 seals, 7 labelled plates, 18 1.5ml tubes, tips, pipettes, and maybe a bag to transport all of this stuff...

First I need to make new 10uM stocks of each primer. I will make tubes that I can pull from twice by making 100ul.

This would be 10ul Primer stock added to 90ul of nfH2O

Next I will make a 1.5ml tube for each primer pair and water:

* 49.5ul of primer FW  
* 49.5ul of primer RV  
* 506ul of nfH20

Pippette 75ul into each well of the column of the PCR primer/water MM correspoding to the primer pair:

* Column 1: 01/02  
* Column 2: --  
* Column 3: 05/04  
* Column 4: --  
* Column 5: 06/07  
* Column 6: --  
* Column 7: 13/14
* Column 8: --
* Column 9: 15/16  
* Column 10: --  
* Column 11: 17/18  
* Column 12: --  

Seal all the plates and maybe put in a bag and transport to the main lab where I already have a program set up on the robot to transfer primer water and Multiplex product into each of the singleplex plates.

Mix and vortex the multiplex plate first before because there is no mixing step on the robot when it takes from the multiplex plate.
